// Code generated by protoc-gen-go-random. DO NOT EDIT.
// versions:
//  - protoc-gen-go-random {{ .PluginVersion }}
//  - protoc         {{ .ProtocVersion }}
// source: {{ .SourcePath }}

package {{ .GoPackageName }}

{{ if .Services }}import (
    "context"
    "math/rand"
    "testing/quick"
	"reflect"
){{ end }}

{{ range $service := .Services }}
type {{ .Name }}RandomServer struct {
    Unimplemented{{ .Name }}Server
    Rand *rand.Rand
}

{{ range .Methods }}
func (r *{{ $service.Name }}RandomServer) {{.Name}}(ctx context.Context, _ *{{ .Input }}) (out *{{ .Output }}, err error) {
    value, _ := quick.Value(reflect.TypeOf(out), r.Rand)

	return value.Interface().(*{{ .Output }}), nil
}
{{ end }}
{{ end }}
