// Code generated by protoc-gen-go-random. DO NOT EDIT.
// versions:
//  - protoc-gen-go-random {{ .PluginVersion }}
//  - protoc         {{ .ProtocVersion }}
// source: {{ .SourcePath }}

package {{ .GoPackageName }}

import (
    "context"
    "math/rand"
    "testing/quick"
    "reflect"
)

{{ range $service := .Services }}
type {{ .Name }}RandomServer struct {
    Unimplemented{{ .Name }}Server
    Rand *rand.Rand
}

{{ range .Methods }}
func (r *{{ $service.Name }}RandomServer) {{.Name}}(ctx context.Context, _ *{{ .Input }}) (*{{ .Output.Name }}, error) {
    out := &{{ .Output.Name }}{}

    {{ range $field := .Output.Fields }}
    randValue(&out.{{ $field }}, r.Rand)
    {{ end }}

	return out, nil
}
{{ end }}
{{ end }}

func randValue[T any](out *T, r *rand.Rand) {
	v, _ := quick.Value(reflect.ValueOf(*out).Type(), r)
	*out = v.Interface().(T)
}
