# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProtocGenGoRandom < Formula
  desc ""
  homepage ""
  version "0.2.0"

  depends_on "mkcert" => "1.4.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juliendoutre/protoc-gen-go-random/releases/download/v0.2.0/protoc-gen-go-random_Darwin_x86_64.tar.gz"
      sha256 "813fa0fa53ac1163493bfbdf762826afa0982a2350bf9dd909517c9b4f71d45f"

      def install
        bin.install "protoc-gen-go-random"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juliendoutre/protoc-gen-go-random/releases/download/v0.2.0/protoc-gen-go-random_Darwin_arm64.tar.gz"
      sha256 "2d2f5a00a8006954d28968a71448354e4b8c38e89efe7327622cb8e4990ed671"

      def install
        bin.install "protoc-gen-go-random"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/juliendoutre/protoc-gen-go-random/releases/download/v0.2.0/protoc-gen-go-random_Linux_x86_64.tar.gz"
        sha256 "570a90e2391e2dfb9afb1a857c682172a918ed343572fc2e7bc5f45316543b9f"

        def install
          bin.install "protoc-gen-go-random"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/juliendoutre/protoc-gen-go-random/releases/download/v0.2.0/protoc-gen-go-random_Linux_arm64.tar.gz"
        sha256 "3a838922adca67a1a0e40bcbddd569c5537cfacfe03f5246da9262ed90851e27"

        def install
          bin.install "protoc-gen-go-random"
        end
      end
    end
  end
end
