# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProtocGenGoRandom < Formula
  desc ""
  homepage ""
  version "0.1.0"

  depends_on "mkcert" => "1.4.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juliendoutre/protoc-gen-go-random/releases/download/v0.1.0/protoc-gen-go-random_Darwin_x86_64.tar.gz"
      sha256 "cbf20422270ad896df9191e9ebc98cf17c448475f20697d6ea7ffdb1f7333e9f"

      def install
        bin.install "protoc-gen-go-random"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juliendoutre/protoc-gen-go-random/releases/download/v0.1.0/protoc-gen-go-random_Darwin_arm64.tar.gz"
      sha256 "6ce29dd0960d0cc3bf00314f160ff637f0800227d1af3bcdb3f011bd7820ba8e"

      def install
        bin.install "protoc-gen-go-random"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/juliendoutre/protoc-gen-go-random/releases/download/v0.1.0/protoc-gen-go-random_Linux_x86_64.tar.gz"
        sha256 "24e5363a75147c04a2f6661990fe0451aabb79fb65890117a4f1335c65a8fd51"

        def install
          bin.install "protoc-gen-go-random"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/juliendoutre/protoc-gen-go-random/releases/download/v0.1.0/protoc-gen-go-random_Linux_arm64.tar.gz"
        sha256 "501cff95b75dd5bbe478a18bb7b9647b302568f85b695135701e5e6df5fc8f9a"

        def install
          bin.install "protoc-gen-go-random"
        end
      end
    end
  end
end
