// Code generated by protoc-gen-go-random. DO NOT EDIT.
// versions:
//  - protoc-gen-go-random (unknown)
//  - protoc         v5.29.3
// source: example/api.proto

package pb

import (
	"context"
	"math/rand"
	"testing/quick"
	"reflect"
)

type HelloWorldRandomServer struct {
	UnimplementedHelloWorldServer
	Rand *rand.Rand
}

func (r *HelloWorldRandomServer) Greet(ctx context.Context, _ *GreetRequest) (out *GreetResponse, err error) {
	value, _ := quick.Value(reflect.TypeOf(out), r.Rand)

	return value.Interface().(*GreetResponse), nil
}
